// Generated by CoffeeScript 1.9.1
var Hapi, exec;

exec = require("child_process").exec;

Hapi = require("hapi");

exec("npm i", function() {
  var server;
  server = new Hapi.Server();
  server.connection({
    port: 8080
  });
  server.route({
    method: "GET",
    path: "/",
    config: {
      handler: {
        file: "./public/templates/index.html"
      }
    }
  });
  server.route({
    method: "GET",
    path: "/{path*}",
    config: {
      handler: {
        directory: {
          path: "./public/"
        }
      }
    }
  });
  return server.start(function() {
    return console.log("Server running at:", server.info.uri);
  });
});
