// Generated by CoffeeScript 1.9.1
var Hapi, server;

Hapi = require("hapi");

server = new Hapi.Server();

server.connection({
  port: 80
});

server.route({
  method: "GET",
  path: "/{path*}",
  config: {
    handler: {
      directory: {
        path: "./public/"
      }
    }
  }
});

server.start(function() {
  return console.log("Server running at:", server.info.uri);
});
