// Generated by CoffeeScript 1.9.1
var Hapi, exec, isDev, startServer;

exec = require("child_process").exec;

Hapi = require("hapi");

isDev = process.argv[2];

exec("npm prune", function() {
  return exec("npm i", function() {
    if (isDev) {
      exec("jade -w .");
      exec("sass -w .");
      return exec("coffeescript-concat -I ./public/js -o ./public/js/app", function() {
        return exec("coffee -cb ./public/js/app", function() {
          return startServer();
        });
      });
    } else {
      return startServer();
    }
  });
});

startServer = function() {
  var server;
  server = new Hapi.Server();
  server.connection({
    address: "0.0.0.0",
    port: 8080
  });
  server.route({
    method: "GET",
    path: "/",
    config: {
      handler: {
        file: "./public/templates/index.html"
      }
    }
  });
  server.route({
    method: "GET",
    path: "/{path*}",
    config: {
      handler: {
        directory: {
          path: "./public/"
        }
      }
    }
  });
  return server.start(function() {
    return console.log("Server running at:", server.info.uri);
  });
};
